- name: Add Bash Aliases
  copy: 
    src: ./configs/.bash_aliases
    dest: ~/

- name: Add Functions
  copy: 
    src: ./configs/.functions
    dest: ~/

- name: Add Tmux Config
  copy: 
    src: ./configs/.tmux.conf
    dest: ~/

- name: Add Ctags
  copy: 
    src: ./configs/.ctags
    dest: ~/

- name: Make neovim config file
  local_action:
    module: file
    path: ~/.config/nvim
    state: directory

- name: Copy vim config for neovim
  copy:
    src: ./configs/init.vim
    dest: ~/.config/nvim/init.vim