- name: Copy Config to bashrcs
  blockinfile:
    path: "{{ item.path }}" 
    block: |
      NODE_ENV=development

      if [ -f ~/.bash_aliases ]; then
        source ~/.bash_aliases
      fi
      if [ -f ~/.functions ]; then
        source ~/.functions
      fi
      if [ -f ~/.terminal_changes ]; then
        source ~/.terminal_changes
      fi

      # TODO: Modify these paths to point to the actual location
      export PATH="$PATH:$HOME/path/to/scripts"
      export PATH="$PATH:$HOME/path/to/scripts-local"
      export PATH="$PATH:$HOME/path/to/git-container"

  with_items:
    - { path: '~/.bashrc' }
    - { path: '~/.zshrc' }
