
- name: Download VS Code
  ansible.builtin.shell:  apt-get install wget gpg

- name: Download VS Code
  ansible.builtin.shell:  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg

- name: Download VS Code
  ansible.builtin.shell: install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d

- name: Download VS Code
  ansible.builtin.shell: sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'

- name: Download VS Code
  ansible.builtin.shell: rm -f packages.microsoft.gpg

- name: Install Package
  ansible.builtin.shell: apt install apt-transport-https

- name: Update Package
  ansible.builtin.shell: apt update

- name: Install Code
  ansible.builtin.shell: apt install -y code