- hosts: localhost
  become: true
  vars:
    the_user: "{{ ansible_user_id }}"
  pre_tasks:
    - name: Update APT
      apt:
        update_cache: true
  tasks:
    - name: Install Packages
      include_tasks: tasks/packages.yml
    - name: Setup ZSH
      include_tasks: tasks/zsh.yml
    - name: Setup Node
      include_tasks: tasks/node.yml
    - name: Setup VIM
      include_tasks: tasks/vim.yml
    - name: Setup FZF
      include_tasks: tasks/fzf.yml
    - name: Setup Dot Files
      include_tasks: tasks/profiles.yml
    - name: Setup GIT
      include_tasks: tasks/git.yml
